{ config, pkgs, lib, ... }:

{
  # AMD GPU configuration
  hardware.opengl = {
    enable = true;
    driSupport = true;
    driSupport32Bit = true;
    extraPackages = with pkgs; [
      vaapiVdpau
      libvdpau-va-gl
      intel-media-driver
      intel-vaapi-driver
      mesa
      mesa.drivers
      mesa.drivers32
    ];
  };

  # Enable AMD GPU tools
  environment.systemPackages = with pkgs; [
    # AMD GPU control tools
    corectrl
    lact
    radeontop
    amdgpu-pro
    mesa-demos
    glxinfo
    vulkan-tools
    
    # Fan control
    fancontrol
    lm_sensors
    
    # Monitoring
    mangohud
    goverlay
    gwe
    
    # Performance tools
    gamemode
    gamescope
    
    # Testing tools
    glmark2
    unigine-valley
    unigine-heaven
  ];

  # Enable AMD GPU features
  hardware.amdgpu = {
    enableGcn = true;
    enableDc = true;
  };

  # Enable kernel modules
  boot.kernelModules = [ "amdgpu" "kvm-amd" ];

  # AMD performance tweaks
  boot.kernelParams = [
    "amdgpu.ppfeaturemask=0xffffffff"
    "amdgpu.dcdebugmask=0x200"
    "amdgpu.dpm=1"
    "amdgpu.msi=1"
    "amdgpu.audio=1"
  ];

  # Enable fan control service
  services.fancontrol.enable = true;
  
  # AMD GPU fan control configuration
  environment.etc."fancontrol" = {
    text = ''
      # Configuration file generated by pwmconfig
      INTERVAL=10
      DEVPATH=hwmon0=devices/pci0000:00/0000:00:01.0/0000:01:00.0/hwmon/hwmon1
      DEVNAME=hwmon0=amdgpu
      FCTEMPS=hwmon0/pwm1=hwmon0/temp1_input
      FCFANS=hwmon0/pwm1=hwmon0/fan1_input
      MINTEMP=hwmon0/pwm1=30
      MAXTEMP=hwmon0/pwm1=85
      MINSTART=hwmon0/pwm1=50
      MINSTOP=hwmon0/pwm1=25
      MINPWM=hwmon0/pwm1=0
      MAXPWM=hwmon0/pwm1=255
    '';
  };

  # CoreCtrl configuration
  systemd.services.corectrl = {
    description = "CoreCtrl daemon";
    serviceConfig = {
      Type = "dbus";
      BusName = "org.corectrl.corectrl.helper";
      ExecStart = "${pkgs.corectrl}/bin/corectrl-helper";
      User = "root";
    };
  };

  # LACT configuration
  systemd.services.lact = {
    description = "LACT daemon";
    serviceConfig = {
      Type = "simple";
      ExecStart = "${pkgs.lact}/bin/lact daemon";
      User = "root";
    };
  };
}